name: Upload to CurseForge

on:
    push:
        branches:
            - main # Cambia si usas otra rama principal

jobs:
    upload-addon:
        runs-on: ubuntu-latest

        steps:
            # 1. Descarga el código del repositorio
            - name: Checkout repository
              uses: actions/checkout@v3

            # 2. Obtener el nombre del repositorio
            - name: Get repository name
              run: echo "repo_name=$(basename ${{ github.repository }})" >> $GITHUB_ENV

            # 3. Leer la versión del archivo .toc y convertir interface a game_versions
            - name: Extract version and format game versions
              run: |
                  version=$(grep -Po "(?<=## Version: )\d+\.\d+\.\d+" ${{ env.repo_name }}.toc)
                  interface=$(grep -Po "(?<=## Interface: )\d+" ${{ env.repo_name }}.toc)
                  major=$((interface / 10000))
                  minor=$(( (interface % 10000) / 100 ))
                  patch=$((interface % 100))
                  game_version="${major}.${minor}.${patch}"
                  echo "addon_version=$version" >> $GITHUB_ENV
                  echo "game_version=$game_version" >> $GITHUB_ENV

            # 4. Crear el archivo ZIP con el formato "nombre-versión.zip"
            - name: Create addon ZIP
              run: |
                  zip -r "${{ env.repo_name }}-${{ env.addon_version }}.zip" . \
                    --exclude "*/.git*" "*/README.md" "*/CHANGELOG.md"

            # 5. Leer el contenido del archivo CHANGELOG.md
            - name: Read CHANGELOG.md
              run: |
                  changelog=$(cat CHANGELOG.md)
                  echo "changelog=$changelog" >> $GITHUB_ENV

            # 6. Subir el archivo ZIP a CurseForge
            - name: Upload to CurseForge
              uses: itsmeow/curseforge-upload@v3.1.2
              with:
                  token: ${{ secrets.CURSEFORGE_API_KEY }}
                  project_id: ${{ secrets.CURSEFORGE_PROJECT_ID }}
                  game_endpoint: "wow"
                  game_versions: "${{ env.game_version }}"
                  file_path: "${{ env.repo_name }}-${{ env.addon_version }}.zip"
                  changelog: "${{ env.changelog }}"
                  changelog_type: markdown
                  release_type: release
